---
# Det these parameters to control the name, region, keypair, and size of the droplet we are launching
droplet_name: "nomad-cluster"
size_id: "1gb"
region_id: "lon1"

# Weave
nomad_url: https://releases.hashicorp.com/nomad/0.3.1/nomad_0.3.1_linux_amd64.zip
nomad_dir: /usr/local/bin/
nomad_bin: nomad

# Don't change the varibles below unless you want experiment
image_id: "ubuntu-14-04-x64"
ssh_pub_key: "{{ lookup('env','SSHKEY') }}"